#!/bin/bash -eu

die() {
    echo "FATAL: $*" >&2
    exit 1
}

usage() {
cat << EOF
usage: vcr [-h] [-r REQUIRE] [-o OUTPUT_FMT] [-g GEOMETRY] [-p PROMPT]
           [-f FONT_SIZE] [-c COMMENT] [SCRIPT]

positional arguments:

    SCRIPT          The script to create the VHS tape. If not given,
                    will read form standard input.

options:

    -h              display this message and exit
    -r REQUIRE      add a command that is required for the tape creation
                    (May be used multiple times.)
    -o OUTPUT_FMT   the output file format (default: webm)
    -g GEOMETRY     the output window geometry (WxH) in pixels
                    (default: 1200x800)
    -p PROMPT       The regex for the command prompt for 'Wait'
    -f FONT_SIZE    the font size (default: 16)
    -c COMMENT      the time to wait after a comment is displayed
                    (default: 5s)

    -t              Output a template script to stdout

EOF
}

quiet() {
    "$@" >/dev/null 2>/dev/null
}

template_script() {

    cat <<EOF
#!/bin/bash -eu

# vcr: -- This script was used to create the demo video using VCR.
# vcr: -- Check the repository at https://github.com/rjeffman/vcr

# vcr: sleep=3s  -- give the video some lead
# vcr: hide  -- Cleanup environment

# vcr: show clear  -- It's nice to always 'clear' at the end of setup
# vcr: -- Add your demo script here.

# vcr: hide  -- Cleanup environment
# vcr: sleep=3s  -- give the video some lead

# vcr: --
# vcr: -- The options manual
# vcr: --
# vcr: -- hide: Disable screen output
# vcr: -- show: Enable screen output
# vcr: -- clear[=<time>]: clear the screen after <time>
# vcr: -- sleep[=<time>]: wait <time>
# vcr: -- prompt=/<regex>/: Set the "prompt" that marks end of command
# vcr: -- timeout=<time>: Set time to wait for the next command to finish
# vcr: -- stdin=<textline>: Type <textline> for the next command stdin
# vcr: --
# vcr: -- <time>: Can be 's' (seconds), 'm' (minutes) or 'ms' (miliseconds)
# vcr: -- "stdin" must be the last command on the line
# vcr: -- Multiple commands can be used like "# vcr: show clear sleep=500ms"
EOF
}

# defaults
PRECUT="2s"    # seconds before demo start
POSTCUT="1s"  # seconds at demo end
WIDTH="1200"  # screen width
HEIGHT="800"  # screen height
FONT="16"     # font size
FORMAT="webm" # output format
DEFAULT_PROMPT='/.*[\$#] *$/'  # default prompt regex for Wait
COMMENT_SLEEP="5s"   # Default time to display comments
CLEAR_TIME="3s"      # Default time before clearing screen

declare -a REQUIRES=()

# Handle CLI options
while getopts ":hc:f:g:o:p:r:t" option
do
    case "${option}" in
        h) usage ; exit 0 ;;
        c) COMMENT_SLEEP="${OPTARG}" ;;
        f) FONT="${OPTARG}" ;;
        g)
            WIDTH="$(cut -dx -f1 <<< "${OPTARG}")"
            HEIGHT="$(cut -dx -f2 <<< "${OPTARG}")"
        ;;
        o) FORMAT="${OPTARG}" ;;
        p) DEFAULT_PROMPT="/${OPTARG}/" ;;
        r) REQUIRES+=("${OPTARG}") ;;
        t) template_script ; exit 0 ;;
        *) die "Invalid option: ${OPTARG}" ;;
    esac
done

shift $((OPTIND - 1))
[[ $# -le 1 ]] || die "Only one script can be processed at a time."

# script to execute
SCRIPT="${1:-"-"}"

# output file
if [[ "${SCRIPT}" == "-" ]]
then
    OUTPUT="out.${FORMAT}"
else
    [[ -f "${SCRIPT}" ]] || die "Script '${SCRIPT}' not found."
    OUTPUT="$(basename "${SCRIPT}" | cut -d. -f 1).${FORMAT}"
fi

# check dependencies
for cmd in vhs "${REQUIRES[@]}"
do
    # shellcheck disable=SC2310
    quiet command -v "${cmd}" || die "Cannot find '${cmd}' executable on PATH"
done

# tape header.
cat <<EOF
Output ${OUTPUT}
Set FontSize ${FONT}
Set Width ${WIDTH}
Set Height ${HEIGHT}
EOF

# Requires
for req in "${REQUIRES[@]}"
do
    echo "Require ${req}"
done

# Start recording
echo "Sleep ${PRECUT}"

# Initialize VCR vars
PROMPT=" ${DEFAULT_PROMPT}"
WAIT="${PROMPT}"
REM=""
SLEEP=""
TEXTLINE=""

# shellcheck disable=SC2312
sed -e '/^#!/d' -e '/^$/d' < "${SCRIPT}" | while read -r line
do
    if [[ "${line}" == "# vcr:"* ]]
    then
        line="${line//--*/}"
        if [[ "${line}" =~ "clear" ]]
        then
            # shellcheck disable=SC2001,SC2312
            CLEAR="$(sed -e 's#.*\(clear[^ ]*\).*#\1#' <<< "${line}" | cut -d= -f2)"
            if [[ -z "${HIDE}" ]]
            then
                [[ "${CLEAR}" == "clear" ]] && echo "Sleep ${CLEAR_TIME}" || echo "Sleep ${CLEAR}"
            fi
            echo "Ctrl+L"
        fi
        [[ "${line}" =~ "hide" ]] && echo "Hide" && HIDE="hidden"
        if [[ "${line}" =~ "show" ]] && [[ -n "${HIDE}" ]]
        then
            HIDE=""
            echo "Show"
        fi
        if [[ "${line}" =~ "wait" ]]
        then
            # shellcheck disable=SC2001
            WAIT="$(sed -e 's#.*wait="\([^"]*\)".*#\1#' <<< "${line}")"
        fi
        if [[ "${line}" =~ "sleep" ]]
        then
            # shellcheck disable=SC2001
            SLEEP="$(sed -e 's#.*sleep=\([^ ]*\).*#\1#' <<< "${line}")"
        fi
        if [[ "${line}" =~ "prompt" ]]
        then
            # shellcheck disable=SC2001
            PROMPT="$(sed -e 's#.*prompt=\(/[^/]*/\).*# \1#' <<< "${line}")"
        fi
        if [[ "${line}" =~ "timeout" ]]
        then
            # shellcheck disable=SC2001
            WAIT="@$(sed -e 's#.*timeout=\([^ ]*\).*#\1#' <<< "${line}") ${PROMPT}"
        fi
        if [[ "${line}" =~ "stdin" ]]
        then
            # shellcheck disable=SC2001
            TEXTLINE="$(sed -e 's#.*stdin=\(.*\)#\1#' <<< "${line}")"
        fi
        continue
    fi
    # Run 'noop' commands for displaying comments
    if [[ "${line}" == "#"* ]]
    then
        # do not show comments if commands are hidden
        [[ -n "${HIDE:-}" ]] && continue
        REM='`'
    fi
    # Run and wait for command
    grep -q "\"" <<< "${line}" && echo "Type '${REM}${line}${REM}'" || echo "Type \"${REM}${line}${REM}\""
    [[ -z "${HIDE:-}" ]] && echo -e "Sleep 500ms"
    echo "Enter"
    if [[ -n "${TEXTLINE:-}" ]]
    then
        echo "Type '${TEXTLINE}'"
        [[ -z "${HIDE:-}" ]] && echo -e "Sleep 500ms"
        echo "Enter"
    fi
    if [[ -n "${REM:-}" ]]
    then
        echo "Sleep ${SLEEP:-${COMMENT_SLEEP}}"
    else
        [[ -z "${SLEEP:-}" ]] && echo "Wait${WAIT}" ||  echo "Sleep ${SLEEP}"
    fi

    # Reset VCR vars
    PROMPT=" ${DEFAULT_PROMPT}"
    WAIT="${PROMPT}"
    REM=""
    SLEEP=""
    TEXTLINE=""
done

echo "Sleep ${POSTCUT}"
